version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - "local"
    
  dbadmin:
      container_name: "db-admin"
      image: aaronshaf/dynamodb-admin
      ports: 
        - "8000:8000"
        - "8001:8001"
      environment:
        DYNAMO_ENDPOINT: http://localstack:4566
        AWS_REGION: ${AWS_REGION:-local}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-local}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-local}
      depends_on:
      - "localstack"
      networks:
      - "local"

networks:
  local:
    driver: "bridge"




